### ISSUE TITLE
Conceptos téoricos

### ISSUE THREAD

**Issue by avp0038** [avp0038/GESPRO_Practicas#10]
- Calidad del software
- Medidas de código

Utilizar referencia Medición para la gestión en la ingeniería del software

Autor: José Javier Dolado Cosín; Luis Fernández Sanz Editorial: Madrid : RA-MA, ©2000. Edición/Formato: Print book : Español (spa)Ver todas las ediciones y todos los formatos Base de datos: WorldCat

**Comment by dds0007** [comment]
repasados y revisados
